/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "../Stm32_F103C6_Drivers/inc/stm32f103x6.h"
#include "../Stm32_F103C6_Drivers/inc/stm32F103C6_GPIO_Driver.h"
#include "../Stm32_F103C6_Drivers/inc/stm32_F103C6_EXTI_Driver.h"
#include "../HAL/inc/keypad.h"
#include "../HAL/inc/lcd.h"


uint8_t clearFlag =0;

int VAL1 = 3;
int VAL2 = 7;
int VAL3 = 0;
uint8_t CTRL_VAL =1;
uint8_t IPSR_VAL =0;

void EXTI9_CallBack (void)
{
	clearFlag = 1;
	__asm("MRS %[out0], IPSR"	//lab6 : reading IPSR value in IPSR_VAL
			:[out0] "=r" (IPSR_VAL));



}
int main(void)
{
	//CLK Enable
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

	EXTI_PinConfig_t EXTI_Config ;

	EXTI_Config.EXTI_PIN = EXTI9PB9;
	EXTI_Config.IRQ_EN = EXTI_IRQ_ENABLE;
	EXTI_Config.Trigger_Case = EXTI_Trigger_Rising;
	EXTI_Config.P_IRQ_CallBack = EXTI9_CallBack;

	MCAL_EXTI_GPIO_Init(&EXTI_Config);

	__asm("nop \n\t nop \n\t nop");  //lab1 		//write instructions in a single line
	//nop: no operation
	//dump instruction usually used to make delays with specific time
	//making the cpu take time = instruction time * no. nop




	__asm("nop \n\t "
			"nop \n\t"
			" nop");		//write instructions in multiple lines



	__asm("mov %0, #0xFF"		//lap2		//moving 0xFF in the VAL1 variable , %0 means first parameter
			: "=r" (VAL1)); // output parameters
	//"=" --> means write only
	//"r" --> means use general purpose registers


	__asm("mov R0, %0"		//lap3		//moving VAL1 in the R0 register , %0 means first parameter
			: 					// output parameters
			: "r" (VAL1)); 	// input parameters
	//"r" --> means use general purpose registers (write and read)


	__asm("add %[out0], %[in0], %[in1]"//lap4	//add VAL1 and VAL2 in VAL3
			: [out0] "=r" (VAL3)					// output parameters
			  : [in0] "r" (VAL1), [in1] "r" (VAL2)); 	// input parameters
		//"r" --> means use general purpose registers (write and read)


	__asm("MRS %[out0], CONTROL"	//lab6 : reading IPSR value in CTRL_VAL
			:[out0] "=r" (CTRL_VAL));

	/* Loop forever */
	for(;;)
	{
		if (clearFlag==1)
			clearFlag=0;
	}
}
