/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#define GPIOA_BASE 	 0x40010800
#define GPIOA_CRH	 *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR	 *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_IDR	 *(volatile uint32_t *)(GPIOA_BASE + 0x08)
#define GPIOA_CRL	 *(volatile uint32_t *)(GPIOA_BASE + 0x00)

#define GPIOB_BASE 	 0x40010C00
#define GPIOB_CRH	 *(volatile uint32_t *)(GPIOB_BASE + 0x04)
#define GPIOB_ODR	 *(volatile uint32_t *)(GPIOB_BASE + 0x0C)
#define GPIOB_IDR	 *(volatile uint32_t *)(GPIOB_BASE + 0x08)
#define GPIOB_CRL	 *(volatile uint32_t *)(GPIOB_BASE + 0x00)

#define RCC_BASE  	 0x40021000
#define RCC_APB2ENR  *(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR  	 *(volatile uint32_t *)(RCC_BASE + 0x4)
#define RCC_CR  	 *(volatile uint32_t *)(RCC_BASE)

void clock_init (void){
	//init clock for GPIOA
	RCC_APB2ENR |= 1<<2;

	//init clock for GPIOB
	RCC_APB2ENR |= 1<<3;


}

void GPIO_init(void)
{
	GPIOA_CRL = 0;
	GPIOA_CRH = 0;
	GPIOA_ODR = 0;

	//input init
	//PA1 floating input
	GPIOA_CRL &= ~(0b11 << 4);
	GPIOA_CRL |= (1 << 6);

	//PA13 floating input
	GPIOA_CRH &= ~(0b11 << 20);
	GPIOA_CRH |= (1 << 22);

	//output init
	//PB1 push pull mode (Output mode, max speed 10 MHz)
	GPIOB_CRL |= (1<<4);
	GPIOB_CRL &= ~(0b11 << 6);
	//PB13 push pull mode (Output mode, max speed 10 MHz)
	GPIOB_CRH |= (1<<20);
	GPIOB_CRH &= ~(0b11 << 22);

}

void wait (unsigned int time)
{
	unsigned int i,j;
	for(i=0;i<time;i++)
		for(j=0;j<255;j++);
}

int main(void)
{
	clock_init();
	GPIO_init();


	while(1)
	{
		if (((GPIOA_IDR & (1<<1))>>1) == 0)
		{
			GPIOB_ODR ^= (1<<1);
			while (((GPIOA_IDR & (1<<1))>>1) == 0);
		}
		if (((GPIOA_IDR & (1<<13))>>13) == 1)
		{
			while(((GPIOA_IDR & (1<<13))>>13) == 1)
			{
				GPIOB_ODR ^= (1<<13);
				wait(1);
			}
		}


	}
}
