/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "../Stm32_F103C6_Drivers/inc/stm32f103x6.h"
#include "../Stm32_F103C6_Drivers/inc/stm32F103C6_GPIO_Driver.h"
#include "../Stm32_F103C6_Drivers/inc/stm32_F103C6_EXTI_Driver.h"
#include "../HAL/inc/keypad.h"
#include "../HAL/inc/lcd.h"


uint8_t clearFlag =0;
void my_wait (int x)
{
	int i , j;
	for (i=0; i<x ; i++)
		for (j=0; j<=255 ; j++);
}
void EXTI9_CallBack (void)
{
	clearFlag = 1;
	LCD_WRITE_STRING("Hello taftaf <33 ..");
//	my_wait(500);
}
int main(void)
{
	//CLK Enable
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

	LCD_INIT();
	LCD_clear_screen();

	EXTI_PinConfig_t EXTI_Config ;

	EXTI_Config.EXTI_PIN = EXTI9PB9;
	EXTI_Config.IRQ_EN = EXTI_IRQ_ENABLE;
	EXTI_Config.Trigger_Case = EXTI_Trigger_Rising;
	EXTI_Config.P_IRQ_CallBack = EXTI9_CallBack;

	MCAL_EXTI_GPIO_Init(&EXTI_Config);

    /* Loop forever */
	for(;;)
	{
		if (clearFlag==1)
		{
			LCD_clear_screen();
			clearFlag=0;
		}
	}
}
