/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "../Stm32_F103C6_Drivers/inc/stm32f103x6.h"
#include "../Stm32_F103C6_Drivers/inc/stm32F103C6_GPIO_Driver.h"
#include "../Stm32_F103C6_Drivers/inc/stm32_F103C6_EXTI_Driver.h"
#include "../HAL/inc/keypad.h"
#include "../HAL/inc/lcd.h"


uint8_t clearFlag =0;

enum CPU_AccessLevel_e {
	privileged,
	unprivileged
};

void Switch_CPU_AccessLevel (enum CPU_AccessLevel_e Level);


void HardFault_Handler ()
{
	Switch_CPU_AccessLevel(privileged);
}

void EXTI9_CallBack (void)
{
	clearFlag = 1;
}

int main(void)
{
	//CLK Enable
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

	EXTI_PinConfig_t EXTI_Config ;

	Switch_CPU_AccessLevel(unprivileged);	/*if we switch to unprivileged mode before accessing NVIC in EXTI configuration
											the NVIC will not be configured and the exection will jumb to fault handler exception,
											So we will switch to privileged mode in the hard fault handler as I have access on the
											Control Register only in the privilege mode and Handler mode always privileged*/

	EXTI_Config.EXTI_PIN = EXTI9PB9;
	EXTI_Config.IRQ_EN = EXTI_IRQ_ENABLE;
	EXTI_Config.Trigger_Case = EXTI_Trigger_Rising;
	EXTI_Config.P_IRQ_CallBack = EXTI9_CallBack;

	MCAL_EXTI_GPIO_Init(&EXTI_Config);


	/* Loop forever */
	for(;;)
	{
		if (clearFlag==1)
		{
			clearFlag=0;
		}


	}
}

void Switch_CPU_AccessLevel (enum CPU_AccessLevel_e Level)
{
	switch (Level)
	{
	case privileged: //clear CONTROL[0] Register
		__asm("MRS r3, CONTROL \n\t"		//Read
				"LSR r3, r3, #1 \n\t"		// r3 >> 1
				"LSL r3, r3, #1 \n\t"		// r3 << 1		== r3 &= ~(r3 << 0)
				"MSR CONTROL, r3"	);		//Write
		break;

	case unprivileged: //Set CONTROL[0] Register
		__asm("MRS r3, CONTROL \n\t"		//read
				"ORR r3, r3, #0x1 \n\t"		//modify
				"MSR CONTROL, r3"	);		//write
		break;
	}
}
