/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#define GPIOA_BASE 	 0x40010800
#define GPIOA_CRH	 *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR	 *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define RCC_BASE  	 0x40021000
#define RCC_APB2ENR  *(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR  	 *(volatile uint32_t *)(RCC_BASE + 0x4)
#define RCC_CR  	 *(volatile uint32_t *)(RCC_BASE)


int main(void)
{
	//init clock for GPIOA
	RCC_APB2ENR |= 1<<2;

	//PLLMUL:(bits 18:21) PLL multiplication factor
	//0110: PLL input clock x 8
	RCC_CFGR |= (0b0110 << 18);

	//PLLSRC: (bit 16)PLL entry clock source
	//0: HSI oscillator clock / 2 selected as PLL input clock
	RCC_CFGR &= ~(1 << 16);

	//SW:(bits 0:1) System clock switch
	//10: PLL selected as system clock
	RCC_CFGR |= (0b10 << 0);


	//set PPRE2(bits 11:13) to 101: HCLK divided by 4
	RCC_CFGR |=(0b101 << 11);

	//set PPRE1(bits 8:10) to 100:HCLK devided by 2
	RCC_CFGR |= (0b100 <<8);

	//SWS:(bits 2:3) System clock switch status
	//10: PLL used as system clock
	RCC_CFGR |= (0b10 << 2);

	//Bit 24 PLLON: PLL enable
	//1: PLL ON
	RCC_CR |= (1 << 24);

	//Init GPIOA
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	while(1)
	{
		GPIOA_ODR |= 1<<13 ;
		for (int i = 0; i < 5000; i++); // arbitrary delay
		GPIOA_ODR &= ~(1<<13) ;
		for (int i = 0; i < 5000; i++); // arbitrary delay
	}
}
